### ISSUE TITLE
Grafana Alerts for SQLite datasource seems to be broken

### ISSUE THREAD

**Issue by droidbuzz** [fr-ser/grafana-sqlite-datasource#49] opened 2021-07-06 13:27 UTC
**Describe the bug**
Trying to setup alerts for Graph Panel (SQLite Datasource). But the alerting seems to be broken for this plugin - Test alerts are failing with following error:

`tsdb.HandleRequest() error rpc error: code = Unavailable desc = connection error: desc = \"transport: error while dialing: dial unix /tmp/plugin124935319: connect: connection refused\"`

Tried with multiple Notification Channels (Email/PagerDuty/AlertManager) - faced same issue with all.

Note: Tried generating test alert using other Datasources (non-SQLite), seems to be working fine. So the issue is only limited to this particular plugin.

**To Reproduce**

1. Go to Graph Panel
2. Generate a Time-series Graph using SQLite Datasource
3. Edit Panel -> Go to "Alert" Tab
4. Specify a condition which would trigger an alert.
5. Click on "Test Rule".

- OS: Linux
- Run via docker? yes
- Browser: Chrome
- Grafana Version: V7.3.6
- Plugin Version: V1.2.0
- Plugin installed via grafana-cli or manually? Manually

**Additional context**
I was going through the change log - looks like Alerting is enabled/supported for this plugin/datasource since V1.0.1. Wondering if anyone was able to actually generate the alerts - let me know. Thanks.

**Comment by fr-ser** [comment] 2021-07-13 20:56
I am looking into it.
I already found one bug, which is related to the handling of empty query results for time-series data. This can happen often for alerting. (see https://github.com/fr-ser/grafana-sqlite-datasource/commit/e14a4abf247d1488397bb55c09ab94d21fec4130)

Another bug seems to be related to somehow not updating the query from the default value.
This should also make the alerting feature brittle and I am currently investigating that one.

**Comment by fr-ser** [comment] 2021-07-14 20:13
@droidbuzz  would you care to try if the issue is fixed with https://github.com/fr-ser/grafana-sqlite-datasource/releases/tag/v2.0.1-rc.1 ?

In theory that should do the trick. I will test around a bit in the following days and see if it works as I expect it. If you could test it for your use case, however, that would certainly help as well.

**Comment by droidbuzz** [comment] 2021-07-16 14:25
Sure thing - I'll test it over the weekend and report back.

Thanks again for such a quick turnaround - this plugin has been a lifesaver for me. :)

**Comment by fr-ser** [comment] 2021-07-16 17:23
In this implementation (not sure if I'll stick with that one) I support two variables. All other variables are not supported, however, including custom ones.
A bit more info here: https://github.com/fr-ser/grafana-sqlite-datasource/tree/alerting_bug#alerting

I am wondering, though, if I will replace the variables with using a timeFilter macro 🤔

**Comment by fr-ser** [comment] 2021-07-27 12:24
I released the current release candidate without code changes as v2.0.1. 
It will take a while for this version to be available via the Grafana-CLI but I would consider the bug closed for now unless I hear something else 🤷🏻

**Closed by fr-ser** 2021-07-27 12:24 UTC
Labels: bug
